# Generated by Django 6.0.1 on 2026-01-27 13:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#007bff', help_text='Ex: #007bff para azul', max_length=7, verbose_name='Cor (hex)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Formato: (XX) XXXXX-XXXX', regex='^\\([0-9]{2}\\)\\s?[0-9]{4,5}-?[0-9]{4}$')], verbose_name='Telefone')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato: XXX.XXX.XXX-XX', regex='^[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}-[0-9]{2}$')], verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_completo'],
                'indexes': [models.Index(fields=['email'], name='eventos_cli_email_720381_idx'), models.Index(fields=['cpf'], name='eventos_cli_cpf_6514d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_evento', models.DateTimeField(verbose_name='Data do Evento')),
                ('data_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('local', models.CharField(max_length=300, verbose_name='Local')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('capacidade_maxima', models.IntegerField(default=0, verbose_name='Capacidade Máxima')),
                ('valor_ingresso', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Ingresso')),
                ('status', models.CharField(choices=[('planejamento', 'Em Planejamento'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/', verbose_name='Arquivo Excel')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='processando', max_length=20, verbose_name='Status')),
                ('total_linhas', models.IntegerField(default=0, verbose_name='Total de Linhas')),
                ('linhas_importadas', models.IntegerField(default=0, verbose_name='Linhas Importadas')),
                ('linhas_com_erro', models.IntegerField(default=0, verbose_name='Linhas com Erro')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('log_processamento', models.TextField(blank=True, verbose_name='Log de Processamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Importação de Excel',
                'verbose_name_plural': 'Importações de Excel',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_participante', models.CharField(choices=[('vip', 'VIP'), ('comum', 'Comum'), ('staff', 'Staff'), ('palestrante', 'Palestrante')], default='comum', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='pendente', max_length=20, verbose_name='Status')),
                ('codigo_ingresso', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código do Ingresso')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, verbose_name='Forma de Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='eventos.cliente', verbose_name='Cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('txt', 'Texto')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='relatorios/', verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relatório Gerado',
                'verbose_name_plural': 'Relatórios Gerados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['data_evento'], name='eventos_eve_data_ev_e66edd_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['status'], name='eventos_eve_status_df7d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='participante',
            index=models.Index(fields=['status'], name='eventos_par_status_5e3b47_idx'),
        ),
        migrations.AddIndex(
            model_name='participante',
            index=models.Index(fields=['data_inscricao'], name='eventos_par_data_in_26d74d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together={('evento', 'cliente')},
        ),
    ]
